// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Assignment struct {
	ID        int32
	Title     string
	StudentID sql.NullInt32
}

type Class struct {
	ID   int32
	Name string
}

type Student struct {
	ID      int32
	Name    string
	ClassID sql.NullInt32
}
